Add saddu6351's file
saddu6351/github-slideshow pull request #4
Opened 2022-03-24 15:55 UTC by saddu6351

learning how to pull a request

2022-03-24 16:00 UTC, saddu6351 commented
Review  is required  in this pull request

2022-03-24 16:02 UTC, saddu6351 commented
How to assign any reviewer for pull request.

2022-03-24 16:09 UTC, SaadAfzalAzmi requested changes
Good And Fine working

2022-03-24 16:12 UTC, saddu6351 reviewed
done

2022-03-24 16:12 UTC, saddu6351 commented on _posts/0000-01-02-saddu6351.md
> +Your text
info -- "Your name is Saad "

2022-03-24 16:13 UTC, SaadAfzalAzmi approved these changes

2022-03-27 18:44 UTC, saddu6351 reviewed
done and dusted #1

2022-03-27 18:50 UTC, SaadAfzalAzmi approved these changes
ok

2022-03-27 18:50 UTC, SaadAfzalAzmi commented on _posts/0000-01-02-saddu6351.md
> +Your text
that is a good idea to add your info

2022-03-27 18:54 UTC, closed without merging